### PR TITLE
 Remove omnipresent files argument

### LINKED ISSUE #25: Inconsistent CLI syntax for taxa
I just came across something I consider inconsistent: The `grep` command has the following syntax:
```
phyltr grep [taxa] [<options>] [<files>]
```
But this only works because either `taxa` must be specified or an option must be present. Otherwise, the first argument passed as `files` will be assumed to specify `taxa`, which probably fails with "Must specify more than one taxon" (which does not make too much sense) - unless there's a comma in the filename at which point it may get totally weird.

I'd propose to make `taxa` an explicit option, too. This might seem a bit weird, because then we'd **require** at least one **optional argument** - but we might remedy this by allowing `self.taxa` to be empty - which will result in no trees being selected.

### PR DESCRIPTION
**Pull request by xrotwang**
We can even shave off another `@classmethod` - statement count down to 1040.

closes #25

### CODE REVIEW

**Comment by xrotwang** [comment]
@lmaurits what are your thoughts on pep8, btw? I actually found using `flake8` - and sticking to its recommendations - quite liberating; I basically stopped thinking and having an opinion on code style issues, and simply do what the tool tells me.

**Comment by lmaurits** [comment]
> @lmaurits I actually found using `flake8` - and sticking to its recommendations - quite liberating; I basically stopped thinking and having an opinion on code style issues, and simply do what the tool tells me.

War is peace!  Freedom is slavery!  Ignorance is strength! 😛 

Well, I understand what you mean.  After a sufficient number of beers I *will* bitterly complain that standardising on spaces for indentation instead of tabs was a mistake, but realistically I don't think I have any serious objections to anything in PEP8 and I'm sure 90% of my violations of it can be attributed to laziness or ignorance.

Were you proposing integrating `flake8` into tox or Travis or something to enforce compliance?

**Comment by xrotwang** [comment]
I wouldn't want to force it via Travis, I think. But I typically have a line saying run "flake8 src/" in my projects' `RELEASING.md`. So it's a stated goal to be pep8 compliant.
Rather than forcing it, I'd be waiting for [black](https://github.com/python/black) to be available on python 3.5 (or upgrading my python to 3.6), and then just have black reformat everything upon each commit.

**Comment by lmaurits** [comment]
That sounds entirely reasonable to me.

**Pull request merged**
