### PR TITLE
all tests pass on py3.5

### PR DESCRIPTION
**Pull request by xrotwang**
Pretty minimal work so far.

### CODE REVIEW

**Comment by xrotwang** [comment]
@lmaurits I don't know how good the test coverage is for phyltr; but what I'd do next, is switch to using `pytest`, get up to a really high test coverage. Should I continue with this?

**Comment by xrotwang** [comment]
Ah, ok, `PyQt5` isn't something one can easily install. So probably, `phyltr.commands.plot` should import `TreeStyle` conditionally.

**Comment by lmaurits** [comment]
Thanks a lot for doing this porting work!  I'm really glad to see that "phyltr3" is finally possible.

I don't question for a second that you know a lot more than me about modern Python project infrastructure, so I'm sure it's actually normal nowadays - but I was initially surprised by the introduction of a `src` directory.  I seem to recall that the last time I looked into what the broader Python community considered best practice, this was actually something people explicitly discouraged.  But there was far less wide adoption of continuous/automated tooling back then.

**Comment by lmaurits** [comment]
Okay, apparently big happy green "everything works" content around the "merge" button doesn't actually mean that everything is happy.  Travis is now, surprisingly, passing all tests for 3.4 and 3.5 but failing on 2.7 and 3.6.  Seems like a pytest version requirement conflict in both cases?

**Comment by xrotwang** [comment]
Hm. Will have to investigate - the tests did pass on the PR, after all.

**Comment by xrotwang** [comment]
I guess adding a block
```python
    extras_require={
        'dev': ['flake8', 'wheel', 'twine'],
        'test': [
            'mock',
            'pytest>=3.6',
            'pytest-mock',
            'pytest-cov',
            'coverage>=4.2',
        ],
    },
```
in `setup.py` would do the trick. I think this was only introduced in pytest-cov in the latest release 8 hours ago.

**Comment by xrotwang** [comment]
When it comes to python packaging, I came to rely on the judgement of Hynek Schlawack (https://hynek.me/articles/testing-packaging/) - **and** I experienced packaging errors which were not caught by local testing without the intermediate `src` directory.

**Comment by lmaurits** [comment]
Tests are happy now, thanks again!

**Pull request merged**
